### ISSUE TITLE
How to show what fret bar chord is played on

### ISSUE THREAD

**Issue by joshpetit** [joranmulderij/flutter_guitar_tabs#10]
This may be related to #3 , but would it be possible to add the ability to show that he first fret in the tab is the 5th fret for example? All of this would be solvable by allowing fret numbers to be added to the dots in the chart though.

**Comment by joranmulderij** [comment]
The GitHub version of the package has this option. Will update pub.dev after summer. See #7.

**Comment by joranmulderij** [comment]
v0.0.9 on pub.dev now supports this
