### ISSUE TITLE
The grid does not appear in the rendering

### ISSUE THREAD

**Issue by claudemircasa** [joranmulderij/flutter_guitar_tabs#11]
I created a basic widget following the instructions but the grid does not appear during rendering.

![image](https://github.com/joranmulderij/flutter_guitar_tabs/assets/7956750/97967165-c9c0-4a19-a4df-3d1c97d4a903)

My code is like:

```
[other imports...]

import 'package:flutter_guitar_tabs/flutter_guitar_tabs.dart';

class NewCustomWidget extends StatelessWidget {
  final double? width;
  final double? height;

  const NewCustomWidget({
    Key? key,
    this.width,
    this.height,
  }) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return FlutterGuitarTab(
      name: 'Dm',
      tab: 'x 0 0 2 3 1',
    );
  }
}
```

**Comment by joranmulderij** [comment]
I cannot really figure out why this happens. The basic example you provided renders correctly on both windows and web. Could have something to do with Flutter themes that would then be outside of the code snippet provided. Could you provide a minimum reproducible example?

**Comment by claudemircasa** [comment]
The code is as shown but I am using it in FlutterFlow (https://app.flutterflow.io/). I don't understand what could be happening, when I move the mouse over the element's area it seems like it is rendered correctly for a short period of time.

**Comment by joranmulderij** [comment]
I'm not really sure what FlutterFlow does under the hood. It probably uses a complicated theming system. It could help to explicitly set the `color` property. If that does not work, then I don't know what the problem is.

```dart
FlutterGuitarTab(
  name: 'Dm',
  tab: 'x 0 0 2 3 1',
  color: Colors.black,
);
```
