### ISSUE TITLE
Where should I get all the tabs data? 

### ISSUE THREAD

**Issue by alexaung** [joranmulderij/flutter_guitar_tabs#4]
Where should I get all the tabs data? I am using flutter_chord and when user click the chord I want to show the tabs. May I know where can I get all the tabs data?

**Comment by joranmulderij** [comment]
They don't get provided by the package, but here are some links to projects that do provide them. They might not perfectly align with the api of this package, but making them fit should not be too difficult.
I will do an update to support some more diverse input types. I will also add these links to the readme.

- https://github.com/T-vK/chord-collection
- https://gschoppe.com/js/json-chords/

Hope this helps you!

**Comment by alexaung** [comment]
@joranmulderij Thank you so much for json chords and wonderful plugin.

**Comment by joranmulderij** [comment]
The reason I'm not doing this is because it would increase the size of the package. Some users might want to dynamically download the tabs. Forcing data into a package is not a good idea.
