### ISSUE TITLE
Null Safety?

### ISSUE THREAD

**Issue by FlavioBarros13** [joranmulderij/flutter_guitar_tabs#5]
Hi mate great package , creating an app and thinking on integrating this any chance you working on a version with null safety?

Also would be great to be able to style the font colors and background

really great package well done!

**Comment by joranmulderij** [comment]
Thanks for reminding me. I had migrated, but forgot to publish to pub.dev. Version 0.0.8 should now be available and has null safety. It is now also possible to change the color of the font and lines. By wrapping it in a `DecoratedBox` or `Container` you should be able to change the background.

I'm glad you like the package.

**Comment by FlavioBarros13** [comment]
> Thanks for reminding me. I had migrated, but forgot to publish to pub.dev. Version 0.0.8 should now be available and has null safety. It is now also possible to change the color of the font and lines. By wrapping it in a `DecoratedBox` or `Container` you should be able to change the background.
> 
> I'm glad you like the package.

Only one word to describe you brother....Genius! i've recommended the package to few people ...Well done!

**Comment by FlavioBarros13** [comment]
Hi mate..For a later update a major feature would be to also display the Guitar  "FRAT NUMBER) on starting point for starting point location detection if there's no black bar.... the chords show perfectly just some chords are on the upper side(upper octave) of the guitar arm

**Comment by joranmulderij** [comment]
This was one of the things that I removed from the chord.js package, because at the time I could not get it to work. I looked at it again, and found it to work now, but the alignment is a bit off on some of the sizes.

I am not going to publish to pub.dev immediately because I want to fix a few more things, but you can use the updated version of this package by putting this is dependency section of you pubspec.yaml file:

```
flutter_guitar_tabs:
    git:
      url: https://github.com/joranmulderij/flutter_guitar_tabs.git
```

By the way, thanks for the great feedback. If you have any more questions or suggestions, please tell me here.

**Comment by FlavioBarros13** [comment]
> This was one of the things that I removed from the chord.js package, because at the time I could not get it to work. I looked at it again, and found it to work now, but the alignment is a bit off on some of the sizes.
> 
> I am not going to publish to pub.dev immediately because I want to fix a few more things, but you can use the updated version of this package by putting this is dependency section of you pubspec.yaml file:
> 
> ```
> flutter_guitar_tabs:
>     git:
>       url: https://github.com/joranmulderij/flutter_guitar_tabs.git
> ```
> 
> By the way, thanks for the great feedback. If you have any more questions or suggestions, please tell me here.

Yeah been testing and messing with it and saw what you mean but it seems like you are quite close to solving the alignment issue ...  also shared the package to a good number of people and they all loving it really great work

Attached some pic and small vid

![WhatsApp Image 2022-01-15 at 19 44 27](https://user-images.githubusercontent.com/56646534/149632166-1c2cad04-1b54-484d-af8b-ec12d068e9a6.jpeg)

https://user-images.githubusercontent.com/56646534/149632170-36045bd2-1755-496e-b14f-9650cb7f774f.mp4
