### ISSUE TITLE
Can you create tab for ukulele?

### ISSUE THREAD

**Issue by lvsang1504** [joranmulderij/flutter_guitar_tabs#6]

**Comment by joranmulderij** [comment]
I've just tried it, but you should just be able to give the widget data for ukulele chords. The chord won't be exactly centered; I'll do something about that soon.

**Comment by joshpetit** [comment]
I can confirm that you can just input 4 strings and it'll make a ukulele tab, and @joranmulderij is right in pointing out it isn't centered. If something can be done about the centering that'd be awesome!

![image](https://github.com/joranmulderij/flutter_guitar_tabs/assets/59021155/084ba43c-3618-455b-82ce-c0c17b06730c)

**Comment by joranmulderij** [comment]
Ah yea didn't fix that yet. After summer vacation I'll do this. Thanks for verifying.

**Comment by joranmulderij** [comment]
Fixed this and published to pub.dev
